### ISSUE TITLE
refactor: Move `GET /solve/<problem-type>` to `GET /solution/<problem-type>`

### ISSUE THREAD

**Issue by schweikart** [ProvideQ/toolbox-server#46]
We currently have a `GET /solve/<problem-type>` route that can be used to fetch a solution (or just a solution status) from a previous submission to `POST /solve/<problem-type>`. Since the `GET` route cannot be used to to solve a problem but only to fetch a solution, @Elscrux and I agreed to move the `GET` route to `GET /solution/<problem-type>`.

**Comment by Elscrux** [comment]
Will be resolved with #69
